# Generated by Django 5.2.4 on 2025-08-17 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0007_meepreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='meepreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meepreport',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
