# Generated by Django 5.2.4 on 2025-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('report', 'REPORTS'), ('user', 'USER INFORMATION'), ('system', 'SYSTEM INFORMATION')], default='report', max_length=20)),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Administrator Notice',
                'verbose_name_plural': 'Administrator Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
